
name: deploy to ec2
on:
  workflow_run:
      workflows: ["Docker Image CI"]
      types: 
        - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: deploy to ec2
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.EC2HOST }}
              username: ${{ secrets.EC2_USERNAME }}
              key: ${{ secrets.EC2_KEY }}
              script: |
                  sudo docker pull dhruvamaheshwari47/node-app-devops
                  sudo docker rm -f node-app-devops || true
                  sudo docker run -d -p 4000:5000 --name node-app-devops dhruvamaheshwari47/node-app-devops:latest